server:
  port: 8080

spring:
  application:
    name: KSKMessagingService

meta:
  whatsapp:
    # Keep these outside source control in production.
    graph-url: ${META_GRAPH_URL:https://graph.facebook.com}
    graph-version: ${META_GRAPH_VERSION:v23.0}
    phone-number-id: ${META_PHONE_NUMBER_ID:1441298872389202}
    access-token: ${META_ACCESS_TOKEN:EAAXRqmRNuHgBSsPZBSzvu9umOiNRKz29H9S9BLxzFUQdB9apP04JzuKWx60rErx7XTrPUZCh7vTlJz8emCZAuSCkPNZCa9mXuaZC9N2QvICoo4zM5PGjWA2Ll5XvlZAh7p6IH1iDLMPyz6nvGQh64ovXPrx47nqGjqk61MMMJlXD7A0dGbt3xp7QwWk9RMZBggabYwIjriVZCPFw3tqMwl7UVKaDZBuBffF6ZCdeA0xIIR8nbGaYsBXZB04ZBbVow51rhX16SzMk7ecIjVNHmgWvr4wL}
    verify-token: ${META_VERIFY_TOKEN:KSK-MESSAGE-APP_2027}
    app-secret: ${META_APP_SECRET:057bea35bc32f7418735a63b2a37f91e}
    bulk-delay-ms: ${META_BULK_DELAY_MS:100}
    max-batch-size: ${META_MAX_BATCH_SIZE:1000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
