server:
  port: 8080

spring:
  application:
    name: KSKMessagingService

meta:
  whatsapp:
    # Keep these outside source control in production.
    graph-url: ${META_GRAPH_URL:https://graph.facebook.com}
    graph-version: ${META_GRAPH_VERSION:v23.0}
    phone-number-id: ${META_PHONE_NUMBER_ID:1441298872389202}
    access-token: ${META_ACCESS_TOKEN:EAAXRqmRNuHgBStUSGlY5dUgu2tL5rUul5vzWKWZCbZBcHZCYT1CULssfqhSJ0zbbIw0QNojWjZAzWnJJJxi0SkJhSwmKXsdliRFHWy2p9F9SHDo0D1kkmSNRovZC2OiExvO0eqZAxDmeLbp0gk4JKjKKRYdRj8bUYPpENs0cHCBSrD465vc1LhqHYq1ZCr3ZBjZBAZA1QAh3y2VvZCk9jWpiJZA12Jv2ONQwx7ElxZCtyWvzPp1mfJM5FZBZB3owAJs5pQ9kZCzJi07OZClMRtU70LFM4udoz}
    verify-token: ${META_VERIFY_TOKEN:KSK-MESSAGE-APP_2027}
    app-secret: ${META_APP_SECRET:057bea35bc32f7418735a63b2a37f91e}
    bulk-delay-ms: ${META_BULK_DELAY_MS:100}
    max-batch-size: ${META_MAX_BATCH_SIZE:1000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
