server:
  port: 8080

spring:
  application:
    name: KSKMessagingService

meta:
  whatsapp:
    # Keep these outside source control in production.
    graph-url: ${META_GRAPH_URL:https://graph.facebook.com}
    graph-version: ${META_GRAPH_VERSION:v23.0}
    phone-number-id: ${META_PHONE_NUMBER_ID:1441298872389202}
    access-token: ${META_ACCESS_TOKEN:EAAXRqmRNuHgBSuQ8ByATCtgiYS2lQx7ZAMyr3QzDPwQBNT0HqsLDsbl490C1EtwI3Ga2ZBApfHC6iuvoIrmrSC4s6jZBiVUKmKQwSZAMabx0TRRSWhsUZBRisM0K32FZBVZATtMZBCaPvnr3jZBsWaB0ALNtR8I9QUZC2Mo5YIZB79E6kh0NvG5zuECxKgk87rX4AZDZD}
    verify-token: ${META_VERIFY_TOKEN:KSK-MESSAGE-APP_2027}
    app-secret: ${META_APP_SECRET:057bea35bc32f7418735a63b2a37f91e}
    bulk-delay-ms: ${META_BULK_DELAY_MS:100}
    max-batch-size: ${META_MAX_BATCH_SIZE:1000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
